apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-api
spec:
  replicas: 2
  selector:
    matchLabels: { app: cv-api }
  template:
    metadata:
      labels: { app: cv-api }
    spec:
      containers:
        - name: api
          image: ghcr.io/youruser/cv-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cv-secrets
                  key: DATABASE_URL
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 20